### PR TITLE
added Hacktoberfest Countdown

### PR DESCRIPTION
**Pull request by martinh-dev**
I solved the issue #5.

### CODE REVIEW

**Review by rishabhkeshan — CHANGES_REQUESTED** [review]
Hey it would be great if you could make a separate js file for the countdown and also include some styling for it.

**Comment by martinh-dev** [comment]
Would you be so kind to add the "hacktoberfest-accepted" label, if you like the solution?

**Comment by martinh-dev** [comment]
> Hey it would be great if you could make a separate js file for the countdown and also include some styling for it.

Shure. Give me few minutes.

**Comment by martinh-dev** [comment]
> Hey it would be great if you could make a separate js file for the countdown and also include some styling for it.

How do you imagine the styling?

**Comment by rishabhkeshan** [comment]
> > Hey it would be great if you could make a separate js file for the countdown and also include some styling for it.
> 
> How do you imagine the styling?

Hey thats completely upto you, you could add it like a header or any other thing as it pleases along with appropriate styling

**Comment by martinh-dev** [comment]
I added the countdown to the image. Maybe you dont like the color or the font.

**Review by rishabhkeshan — APPROVED** [review]
Great work. I have added the label. Your PR will be merged in sometime.

**Pull request merged**
