### PR TITLE
First PR Challenge 

### PR DESCRIPTION
**Pull request by Nancy4510**
Created my custom profile card from issue #2

### CODE REVIEW

**Comment by rishabhkeshan** [comment]
Hey there are some conflicts, could you please check your code once.

**Comment by Nancy4510** [comment]
Fixed the conflict, hopefully. Please let me know if there are any issues. Thank you.

**Review by rishabhkeshan — APPROVED** [review]
Great Job.

**Comment by Nancy4510** [comment]
Thank you

**Pull request merged**
